spring:
  application:
    name: doctor-office
  # ============================================================================
  # Configuration PostgreSQL Datasource & JPA
  # ============================================================================
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # ============================================================================
  # Configuration Flyway
  # ============================================================================
  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
  # ============================================================================
  # Configuration OAuth2 (Keycloak)
  # ============================================================================
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
# ============================================================================
# Configuration CommonsLoggingRequestFilter
# ============================================================================
logging:
  request:
    include-client-info: true
    include-query-string: true
    include-headers: false
    include-payload: true
    max-payload-length: 1000
# ============================================================================
# Configuration OpenApi & Swagger-UI
# ============================================================================
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
