name: Build & Deploy Doctor-Office-API

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v4
      - name: setup-jdk-21
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: '21'
          cache: 'maven'
      - name: unit-test
        run: mvn -B test --file pom.xml
      - name: package
        run: mvn -B package --file pom.xml